### ISSUE TITLE
A mistake in the abft.html/abft.pdf

### ISSUE THREAD

**Issue by xixisese** [algorandfoundation/specs#24]
In  the section 5.5 Seed in the abft spec, there is descrition as follows:
```
The seed is valid if the following verification procedure succeeds:
    1. Let(B,pk)=Record(L,r−δb,I);let q0 =Seed(L,r−1).
```
It should be : 
   q0 =Seed(L,r−δs). 
not 
   q0 =Seed(L,r−1)

**Comment by derbear** [comment]
Ah, you're right. Good catch!
