### ISSUE TITLE
Min balance check at end of txn group

### ISSUE THREAD

**Issue by gidonkatten** [algorandfoundation/specs#49]
When grouping transactions, if the balance of an account goes below its minimum balance during a transaction within the group then the whole transaction group fails.

Proposal is to allow the minimum balance check to be only performed at the end of the transaction group. This would mean that you have the freedom to structure the order of your transactions in a more clear and concise way.

For example, I may want to have code which acceps the following group txn with an optional fee transfer:

- call to app
- txn from escrow (which raises it min balance eg opt into asset)
- fee of escrow (optional)

The new proposal allows the user to pay for the increase in min balance of the escrow, if the txn from escrow causes its balance to fall below its min balance. You can write concise code since the call to app and txn from escrow is always in posistions 0 and 1 in the group.

**Comment by jannotti** [comment]
I never noticed this issue here before. The proposal is how min balance works already, so it can be closed.

**Comment by gidonkatten** [comment]
@jannotti out of interest, was this always the case?

**Comment by jannotti** [comment]
Yes, it's always been this way.
