### ISSUE TITLE
Formatting of Teal PDF is Difficult to read 

### ISSUE THREAD

**Issue by barnjamin** [algorandfoundation/specs#58]
Page 5 of TEAL.pdf 
![image](https://user-images.githubusercontent.com/520236/140983994-62c1a914-e027-499c-9e4b-5186e73b2c19.png)

Either pandoc template/flags or the way we're formatting it in the markdown should be updated to make this legible

**Comment by abebeos** [comment]
@shane-at-algo , should be closable (latest pdf looks fine)
