### ISSUE TITLE
Potential error in specification

### ISSUE THREAD

**Issue by LokeshaRamesh** [algorandfoundation/specs#80]
In specs/dev/abft.md: 
In section 5.2, (pk, B) is defined
but in section 5.4, (B, pk) is defined

**Comment by abebeos** [comment]
@barnjamin

**Comment by abebeos** [comment]
@fabrice102, could you ping a person that can verify this?

**Comment by fabrice102** [comment]
Thanks for the comment. I've fixed the typo.
