### ISSUE TITLE
The rationale for having late-votes, redo-votes, and down-votes

### ISSUE THREAD

**Issue by vinodganesan** [algorandfoundation/specs#81]
Hi, 

The specification (both the overview and the full specification) seems to use special votes such as late votes, redo-votes, and down-votes (esp. for fast recovery step). However, we couldn't find these votes being absorbed into the consensus protocol in any way (except late vote being used to ignore the Vote received). 

Can you please shed some light on where these votes are being used in the Algorand consensus protocol? Any reference is appreciated.

Thanks,
Vinod

**Comment by fabrice102** [comment]
Hi Vinod,

These special votes are specified in the full specification but it's quite hidden indeed.
And the overview indeed is missing some text about them.

Concretely, all late/redo/down votes act similarly as next votes, just for different thresholds.
They are used for recovery.

See https://github.com/algorandfoundation/specs/blob/6996ac344158ca90a430bc8601fc29b150b0aa3f/dev/abft.md#new-period: all these votes are votes for s > \Cert.

**Comment by abebeos** [comment]
Assuming issue is closeable.

**Comment by barnjamin** [comment]
@abebeos I don't have rights on this repo, I closed the other one because I filed it.

@fabrice102 can probably close this one though

**Comment by fabrice102** [comment]
Agreed. No need to keep it open.
