### ISSUE TITLE
No PDF/HTML available

### ISSUE THREAD

**Issue by abebeos** [algorandfoundation/specs#92]
> [README.md](https://github.com/algorandfoundation/specs#readme)
> View the PDF/HTML from the [latest release](https://github.com/algorandfoundation/specs/releases/latest).

there is not pdf/html

**Comment by shane-at-algo** [comment]
Apologies over that , resolved now via https://github.com/algorandfoundation/specs/pull/93 & https://github.com/algorandfoundation/specs/pull/94
