### ISSUE TITLE
Incorrect date at documentation of Readme.html file

### ISSUE THREAD

**Issue by RushiChavan-dev** [algorandfoundation/specs#99]
At Readme.html file the date is incorrect.
it is showing December 6, 2018 while it should be May 19, 2023

https://github.com/algorandfoundation/specs/releases/tag/abd3d48

![image](https://github.com/algorandfoundation/specs/assets/50754786/95bbca8a-f1bb-4418-bda7-a14ad265aab4)

**Comment by RushiChavan-dev** [comment]
I am happy to fix the issue

**Comment by Howyi888** [comment]
What is this
